# Mac OS X uses path_helper and /etc/paths.d to preload PATH, clear it out first

if [ -x /usr/libexec/path_helper ]; then
    PATH=''
    eval `/usr/libexec/path_helper -s`
fi

export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/Cellar/elixir/1.3.4/bin
export PATH="$HOME/.rbenv/bin:$PATH"
export ASDF_DATA_DIR=`brew --prefix asdf`/
source $ASDF_DATA_DIR/asdf.sh
