source ~/.zsh/prompt.zsh

if which rbenv > /dev/null;
  then eval "$(rbenv init -)";
fi

function git_current_branch() {
  git symbolic-ref HEAD 2> /dev/null | sed -e 's/refs\/heads\///'
}

alias be='bundle exec'
alias gpthis='git push origin HEAD:$(git_current_branch)'
alias grb='git rebase -p'
alias gup='git fetch origin && grb origin/$(git_current_branch)'
alias gm='git merge --no-ff'

# asdf
source /opt/asdf-vm/asdf.sh
source /opt/asdf-vm/completions/asdf.zsh
